Replace jQuery animation for table of contents and remove jQuery package
ember-learn/ember-api-docs pull request #771
Opened 2021-07-31 21:29 UTC by swarajpure

Fixes #769

2021-07-31 21:50 UTC, swarajpure commented on tests/integration/components/table-of-contents-test.js
> +    await click(document.querySelector('.toc-level-0 > a'));
The button is being referred thrice here, will make it into a variable rather than repeating the code

2021-08-01 23:04 UTC, ankushdharkar commented on package.json
> -    "@ember/jquery": "^1.1.0",
❤️

2021-08-01 23:11 UTC, ankushdharkar commented on app/templates/components/table-of-contents.hbs
> +      <ol class="toc-level-1 namespaces selected">
Q: If we have `selected` class applied on this line, do we still want `selected` class applied on line 4 above?

2021-08-01 23:13 UTC, ankushdharkar commented on tests/integration/components/table-of-contents-test.js
> +    assert.dom('ol.toc-level-1').isVisible;
Should `isVisible` be a function call here?
Like [this](https://github.com/simplabs/qunit-dom/blob/master/API.md#examples-10)?

2021-08-01 23:13 UTC, ankushdharkar commented on tests/integration/components/table-of-contents-test.js
> +    assert.dom('ol.toc-level-1').isNotVisible;
Re: `isVisible()`?

2021-08-01 23:13 UTC, ankushdharkar commented on tests/integration/components/table-of-contents-test.js
> +    assert.dom('ol.toc-level-1').isVisible;
Re: `isVisible()`?

2021-08-01 23:14 UTC, ankushdharkar commented on app/styles/components/_sidebar.scss
> +  transition: max-height 0.5s ease;
Should we be animating height or max-height?

2021-08-01 23:15 UTC, ankushdharkar requested changes
Great! Love that you added new tests. Some small queries in the comments.

2021-08-05 12:22 UTC, jenweber commented
Hi! Thanks for your work on this! I agree with Ankush that isVisible should be `isVisible()` instead. Once that is fixed, this will be ready to merge. I tested this locally and it worked great.

2021-08-05 15:10 UTC, swarajpure commented on app/templates/components/table-of-contents.hbs
> +      <ol class="toc-level-1 namespaces selected">
Both are different list elements

2021-08-06 17:42 UTC, swarajpure commented on app/styles/components/_sidebar.scss
> +  transition: max-height 0.5s ease;
We can't actually use height. For the expanded condition, we would have to give `height: auto` and `According to the Mozilla Developer Network docs, auto values have been intentionally excluded from the CSS transitions spec. `
Source: https://css-tricks.com/using-css-transitions-auto-dimensions/

2021-08-06 20:22 UTC, swarajpure commented
> Hi! Thanks for your work on this! I agree with Ankush that isVisible should be `isVisible()` instead. Once that is fixed, this will be ready to merge. I tested this locally and it worked great.

Thanks!
Done with the changes.

Can you please review now @jenweber @ankushdharkar? 😄

2021-08-08 20:42 UTC, jenweber commented
Hi @swarajpure, thanks for your work on this! I see the following failing in CI. I think it's unrelated to your PR and I have opened a separate PR to try and fix it. https://github.com/ember-learn/ember-api-docs/pull/772

```
yarn install v1.22.11
[1/5] Validating package.json...
error ember-api-docs@0.1.0: The engine "yarn" is incompatible with this module. Expected version "1.22.10". Got "1.22.11"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

2021-08-09 19:55 UTC, swarajpure commented
> Hi @swarajpure, thanks for your work on this! I see the following failing in CI. I think it's unrelated to your PR and I have opened a separate PR to try and fix it. #772
> 
> ```
> yarn install v1.22.11
> [1/5] Validating package.json...
> error ember-api-docs@0.1.0: The engine "yarn" is incompatible with this module. Expected version "1.22.10". Got "1.22.11"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Error: Process completed with exit code 1.
> ```

Thanks! Please let me know if there was something done incorrectly from my end. Will fix it 🙂

2021-08-12 12:17 UTC, jenweber approved these changes
I think my PR worked! We'll see. I'll merge your PR in a moment if tests are green.

2021-08-12 12:33 UTC, merged